language: ruby

services:
  - postgresql

env:
  global:
    - RAILS_ENV=test

before_script:
  - cp config/database.yml.travis config/database.yml
  - ./bin/rails db:create
  - ./bin/rails db:schema:load

script:
  - bundle exec rubocop
  - bundle exec rspec